### ISSUE TITLE
lightning-utilities dependency is too strict, package not updated?

### ISSUE THREAD

**Issue by adamjstewart** [conda-forge/pytorch-lightning-feedstock#113]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

We're trying to update the [TorchGeo feedstock](https://github.com/conda-forge/torchgeo-feedstock/pull/10) but we're currently hitting the following issue with `pip check`:
```
pytorch-lightning 1.8.1 has requirement lightning-utilities==0.3.*, but you have lightning-utilities 0.6.0.post0.
```
The recipe listed here actually says `>=0.3` so I'm not sure where it's getting `==0.3.*` from. Maybe the binary on conda-forge wasn't updated because the tests failed?

Also, 1.8.1 is quite old. Are there any plans to update to 1.9.0? Happy to submit a PR to do this but there are already a few auto-opened PRs that haven't been addressed so I don't want to do this if this recipe isn't being maintained anymore.

### Installed packages

```shell
threadpoolctl:               3.1.0-pyh8a188c0_0          conda-forge
    tiledb:                      2.13.2-hd532e3d_0           conda-forge
    timm:                        0.4.12-pyhd8ed1ab_0         conda-forge
    tk:                          8.6.12-h27826a3_0           conda-forge
    torchgeo:                    0.4.0-pyhd8ed1ab_0          local      
    torchmetrics:                0.11.0-pyhd8ed1ab_0         conda-forge
    torchvision:                 0.14.1-cpu_py310hdfb2906_0  conda-forge
    tqdm:                        4.64.1-pyhd8ed1ab_0         conda-forge
    typing-extensions:           4.4.0-hd8ed1ab_0            conda-forge
    typing_extensions:           4.4.0-pyha770c72_0          conda-forge
    tzcode:                      2022g-h166bdaf_0            conda-forge
    tzdata:                      2022g-h191b570_0            conda-forge
    unicodedata2:                15.0.0-py310h5764c6d_0      conda-forge
    urllib3:                     1.26.14-pyhd8ed1ab_0        conda-forge
    werkzeug:                    2.2.2-pyhd8ed1ab_0          conda-forge
    wheel:                       0.38.4-pyhd8ed1ab_0         conda-forge
    xerces-c:                    3.2.4-h55805fa_1            conda-forge
    xorg-kbproto:                1.0.7-h7f98852_1002         conda-forge
    xorg-libice:                 1.0.10-h7f98852_0           conda-forge
    xorg-libsm:                  1.2.3-hd9c2040_1000         conda-forge
    xorg-libx11:                 1.7.2-h7f98852_0            conda-forge
    xorg-libxau:                 1.0.9-h7f98852_0            conda-forge
    xorg-libxdmcp:               1.1.3-h7f98852_0            conda-forge
    xorg-libxext:                1.3.4-h7f98852_1            conda-forge
    xorg-libxrender:             0.9.10-h7f98852_1003        conda-forge
    xorg-renderproto:            0.11.1-h7f98852_1002        conda-forge
    xorg-xextproto:              7.3.0-h7f98852_1002         conda-forge
    xorg-xproto:                 7.0.31-h7f98852_1007        conda-forge
    xz:                          5.2.6-h166bdaf_0            conda-forge
    yaml:                        0.2.5-h7f98852_2            conda-forge
    yarl:                        1.8.2-py310h5764c6d_0       conda-forge
    zipp:                        3.11.0-pyhd8ed1ab_0         conda-forge
    zlib:                        1.2.13-h166bdaf_4           conda-forge
    zstd:                        1.5.2-h3eb15da_6            conda-forge
```

### Environment info

```shell
Not output by conda-forge CI?
```

**Comment by Borda** [comment]
> The recipe listed here actually says `>=0.3` so I'm not sure where it's getting `==0.3.*` from. Maybe the binary on conda-forge wasn't updated because the tests failed?

It could be from `pip` version of the package; not sure... but anyway seems you resolved the issue on your side and merged it, nice :rabbit:

**Comment by adamjstewart** [comment]
> but anyway seems you resolved the issue on your side

That wasn't a fix, that was a hack. TorchGeo doesn't import lightning-utilities so it shouldn't be listed in our feedstock.

Anyway, I see that you've updated this feedstock to the latest version, so perhaps something was fixed and we can remove that hack from our repo. We'll try that in the next release and let you know if there's still an issue.

**Comment by Borda** [comment]
> That wasn't a fix, that was a hack. TorchGeo doesn't import lightning-utilities so it shouldn't be listed in our feedstock.

I am sorry to hear that :(
