### ISSUE TITLE
`pytorch-lightning=1.7` doesn't build against `pytorch=1.12`

### ISSUE THREAD

**Issue by lcolbois** [conda-forge/pytorch-lightning-feedstock#93]
### Comment:

Hello,
I am unsure whether `pytorch-lightning=1.7` is supposed to be compatible with `pytorch=1.12`, but the build is not possible as of now.
E.g:
```
CONDA_OVERRIDE_CUDA=11.2 mamba create -c conda-forge -n test pytorch-lightning=1.7 pytorch=1.12
...
Encountered problems while solving:
  - package pytorch-1.12.0-cpu_py310h75c9ab6_0 requires libprotobuf >=3.20.1,<3.21.0a0, but none of the providers can be installed
```

I think the conflict is between `pytorch=1.12` that seem to require `libprotobuf>=3.20` and this package's `tensorboard>=2.9.1` [constraint](https://github.com/conda-forge/pytorch-lightning-feedstock/blob/main/recipe/meta.yaml#L29) that adds an [underlying pin](https://github.com/conda-forge/tensorboard-feedstock/blob/main/recipe/meta.yaml#L29) to `protobuf < 3.20`. 

I am uncertain whether this can be solved here or should be done in tensorboard or pytorch feedstocks.

Also, is there a way to setup the CI so that it attempts a build with the latest pytorch conda-forge release ?

**Comment by anjos** [comment]
The command above works for me as of today.  What doesn't work, and it seems to be related, is having an environment with both those and tensorflow.  Downgrading pytorch-lightning to 1.5 makes it work again:

```sh
# OK
$ mamba create --dry-run -c conda-forge -n test pytorch-lightning=1.5 pytorch=1.12 tensorflow=2.9

# Not OK
$ mamba create --dry-run -c conda-forge -n test pytorch-lightning=1.7 pytorch=1.12 tensorflow=2.9
```

Any clues?
